// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user.proto

package proto

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *User) Validate() error {
	return nil
}
func (this *GetUserByIdRequest) Validate() error {
	return nil
}
func (this *CreateUserRequest) Validate() error {
	return nil
}
